name: Continuous integration

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Tests
        uses: ./.github/workflows/test.yml
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}

  notification-slack:
    needs: [run-tests]
    if: ${{ needs.run-tests.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send a Slack Message on Success
        uses: ./.github/workflows/notification-slack-aproved.yml
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
