name: Continuous integration

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  run-notificacion:
    needs: [run-tests]
    if: ${{needs.run-tests.result == 'success'}}
    uses: ./.github/workflows/notification-slack-aproved.yml
    secrets: inherit

  deleting-branch:
    needs: [run-notificacion, run-tests]
    if: ${{needs.run-tests.result == 'success'}}
    uses: ./.github/workflows/deleting-aditionalbranches.yml
    secrets: inherit
