name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
  workflow_call:

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          git remote set-url origin "https://github.com/${{ github.repository }}"
          git fetch --prune
          git push origin --delete $branch_name
