name: slack notifcation format error

on: [workflow_dispatch, workflow_call]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
            "blocks":[
               {
                   "type": "section",
                   "text": {
                       "type": "mrkdwn",
                       "text": "🚨🚨🚨 *<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}| Se ha registrado anomalias en formato de codigo en el repositorio: *** ${{github.repository}} *** El cual activo el workflow: **** ${{github.workflow}} ***  Por lo que requiere su revision... Estdo actual: >* Pendiente. 🚨🚨🚨"
                       }
                     }
                   ]
                 }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
