name: Test
on: 
    workflow_call:

jobs: 
    test-action:
     runs-on: ubuntu-lastest
     steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup  Node Environmet 
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'
        - name: Install Dependencies
          run: npm ci
        - name: Check for Formatting Erros
          run: npm run format
        - name: Check for ESlinting Errors
          run: npm run lint
        - name: Check for Type Errors
          run: npm run type-check

    Build:
        runs-on: ubuntu-latest
        needs: test-action
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup  Node Environmet 
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build

    Artefacts-upload: 
        runs-on: ubuntu-latest
        needs: [Build,test-action]
        steps:
            
            - uses: actions/upload-artifact@v3
              with: 
                name: build
                path: .next/
            - name: Run unit Test
              run: npm run test
            - uses: actions/upload-artifact@v3
              if: always()
              with: 
                 name: coverage
                 path: coverage/
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            - name: Install Playwrite Bowsers 
              run: npx playwrite install --with-deps
            - name: Run E2E Test
              run: npm run test:e2e
            - uses: actions/upload-artifact@v3
              if: always()
              with: 
                name: coverplaywrite
                path: playwright-report/
            - name: Send a Slack notificaction
              uses: slackapi/slack-github-action@v1.24.0
              with: 
                payload-file-path: "./.github/test-failure-slack-payload.json"
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                 
            

