name: slack notifcation

on: [workflow_dispatch]

jobs:
   slack:
    runs-on: ubuntu-latest
    steps:
      - name: slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
         payload: |
          {
          "blocks":[
             {
                 "type": "section",
                 "text": {
                     "type": "mrkdwn",
                     "text": "🚨🚨🚨 *<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.workflow}} workflow run >* failed. 🚨🚨🚨"
                 }
             }
          ]
          }
         
          
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK